### PR TITLE
[DR-1305] Periodic updates from http

### PR DESCRIPTION
**Pull request by andresmoschini**
This was an interesting task (at least for me), I had to deal with different framework limitations related to _Tasks_, _HTTP protocol_, _Timers_ and _Testing_.

I think that the result is enough good.

The idea is using it in this way:

```csharp
// Inicialization
var blacklistUrl = "https://raw.githubusercontent.com/MakingSense/safe-browsing/resources/links-blacklist.txt";
var updater = new SimpleRegex.SimpleRegexRulesHttpUpdater(realUrl);
updater.UpdatePeriodically(TimeSpan.FromSeconds(30), TimeSpan.FromMinutes(10));
DIContainer.Register(new SimpleRegex.SimpleRegexUrlChecker(updater.Rules));
```

```csharp
// Another class where I want to check an URL
var checker = DIContainer.Resolve<SimpleRegex.SimpleRegexUrlChecker>();
var url ="https://github.com/MakingSense";
var result = checker.Check(url);
if (!result.IsSafe)
{
    Throw new ApplicationException($"The specified URL ({result.Url} is not safe, it seems to be related to a {result.ThreatType} threat");
}
```

### CODE REVIEW

**Comment by andresmoschini** [comment]
It seems to be something related to CPU busy, do you have an idea about how to continue testing these things and mitigate this issue?

**Comment by andresmoschini** [comment]
It is in a different execution:

**Comment by nreal** [comment]
Great! 👍

**Comment by andresmoschini** [comment]
See the related nuget package in https://preview.nuget.org/packages/MakingSense.SafeBrowsing/0.2.0-alpha1

**Pull request merged**
